const data = [
    {
      id: 0,
      title: 'Multi-Post Stories 1',
      img: 'assest/test.jpg',
      bImg: 'assest/test.jpg',
      view: 'This is the first project card that will appear, looks like the box is in the left, like the figma design, the next box will be in the right i like these dynamic mechanics and is nice looking!',
      desc: 'This is the first big description of this template projects, i will try to do my best to make them all different, but trying to they still have the same lengh, i dont use lorem fo this case so lets see how they result, this is writteng without any application or help of a machine so ejoy reading a lot of human text, this is over 100 lines but is near to the content of the orginal OH we finished.',
      tags: 'Css,Html,Figma,Javascript',
      live: '#',
      repo: '#',
      alt: 'placeholder',
      bAlt: 'Big_Placeholder',
    },
    {
      id: 1,
      title: 'Lasttask Web Store',
      img: 'assest/test.jpg',
      bImg: 'assest/test.jpg',
      view: "This was one of my early projects i did when i was exploring the web development, it's a model of a webstore, have a shopping cart, product pages, account system and everything a store should need.",
      desc: 'This project, have the backend programmed from 0, using php, it does not use any kind of php framework, so the login and database system was made by hand, the use of frameworks for the front end maked this project more faster a easy to do, i used and edited some templates for it, the most important colors in this project are yellow, white and green, i learned a lot with this project so i am happy for done it',
      tags: 'Css,Html,React,PHP',
      live: '#',
      repo: 'https://github.com/eroiyo/lasttask',
      alt: 'placeholder',
      bAlt: 'Big_Placeholder',
    },
    {
      id: 2,
      title: 'Labyrinth-Generator',
      img: 'assest/test.jpg',
      bImg: 'assest/test.jpg',
      view: 'A maze generator using graphs, using a array matrix, commands for vectors, and binary logic to display the letters, this project is filled with tricky programming algroithms that are not commonly use, but when needed are very welcome.',
      desc: 'The graphs are extremely useful when we are talking about machine learning, because they are the perfect representation for a route of desicions, with it, we can automatize any activity, also they are useful when you are trying to do certain kind of simulations, in this project a lot of conditionals were remplaced simply using binary logic, because all the conditionals only have 2 incomes, so feel free to take the trick,',
      tags: 'Java',
      live: '#',
      repo: 'https://github.com/eroiyo/Labyrinth-Generator',
      alt: 'placeholder',
      bAlt: 'Big_Placeholder',
    },
    {
      id: 3,
      title: 'Calculator',
      img: 'assest/test.jpg',
      bImg: 'assest/test.jpg',
      view: 'This calculator was made to try to look likes a casio calculator, a very early project. with this, I explored the world of javascript functions and use buttons to control and display the resulting information in HTML documents',
      desc: 'An electronic calculator is typically a portable electronic device used to perform calculations, ranging from basic arithmetic to complex mathematics, contain a keyboard with buttons for digits and arithmetical operations; contain buttons to make larger or smaller numbers easier to enter this basic calculators assign only one digit or operation on each button; however, in more specific calculators, a button can perform multi-function working with key combinations.',
      tags: 'Css,Html,Javascript',
      live: 'https://eroiyo.github.io/Calculator/',
      repo: 'https://github.com/eroiyo/Calculator/settings/pages',
      alt: 'calculator',
      bAlt: 'Big_Placeholder',
    },
  ];
  export default data;