const data = [
    {
        id: 0,
        title: 'Car Store',
        subtitle: 'Page using 2 different repositories',
        img: 'images/carhub.png',
        bImg: 'images/carhub.png',
        view: 'This is a page made with Ruby on rails and react using 2 different repositories, one that host the api, and the other that host the front end code, so the code is more easy to mantain',
        desc: 'This is the first big description of this template projects, i will try to do my best to make them all different, but trying to they still have the same lengh, i dont use lorem fo this case so lets see how they result, this is writteng without any application or help of a machine so ejoy reading a lot of human text, this is over 100 lines but is near to the content of the orginal OH we finished.',
        tags: 'Css,Html,React,Ruby on Rails',
        live: '#',
        repo: '#',
        alt: 'placeholder',
        bAlt: 'Big_Placeholder',
    },
    {
        id: 1,
        title: 'Bookstore CMS',
        subtitle: 'React page based in a figma design',
        img: 'images/clone.jpg',
        bImg: 'images/clone.jpg',
        view: "A Bookstore webpage featuring a list including the name, the subtitle, current chapter, progress percentage, options, and a form to add your own books.",
        desc: 'This project, have the backend programmed from 0, using php, it does not use any kind of php framework, so the login and database system was made by hand, the use of frameworks for the front end maked this project more faster a easy to do, i used and edited some templates for it, the most important colors in this project are yellow, white and green, i learned a lot with this project so i am happy for done it',
        tags: 'Css,Html,React',
        live: 'https://dazzling-easley-6afabd.netlify.app/',
        repo: 'https://github.com/eroiyo/React-Bookstore',
        alt: 'placeholder',
        bAlt: 'Big_Placeholder',
    },
    {
        id: 2,
        title: 'Youtube Clone',
        subtitle: 'Html and CSS only page',
        img: 'images/youtube.jpg',
        bImg: 'images/youtube.jpg',
        view: 'A attemp to replicate the youtube site design feautring the searching bar, the comment section, the video recommendation list, and of course, the video player.',
        desc: 'The graphs are extremely useful when we are talking about machine learning, because they are the perfect representation for a route of desicions, with it, we can automatize any activity, also they are useful when you are trying to do certain kind of simulations, in this project a lot of conditionals were remplaced simply using binary logic, because all the conditionals only have 2 incomes, so feel free to take the trick,',
        tags: 'HTML,CSS',
        live: 'https://eroiyo.github.io/Youtube_Clone/',
        repo: 'https://github.com/eroiyo/Youtube_Clone',
        alt: 'placeholder',
        bAlt: 'Big_Placeholder',
    },
    {
        id: 3,
        title: 'Conference Website',
        subtitle: 'Website created using an behance design as reference',
        img: 'images/conference.jpg',
        bImg: 'images/conference.jpg',
        view: 'A Conference webpage, created for an Capstone project to practice our html skills, we should pick a topic and use layout, colors and typographic already defined in a behance design made by Cindy Shin',
        desc: '',
        tags: 'Css,Html,Javascript',
        live: 'https://eroiyo.github.io/Conference-Web/',
        repo: 'https://github.com/eroiyo/Conference-Web',
        alt: 'conference',
        bAlt: 'conference',
    },
];
export default data;