const data = [
    {
        id: 0,
        title: 'Car Store',
        subtitle: 'Page using 2 different repositories',
        img: 'images/carhub.png',
        bImg: 'images/carhub.png',
        view: 'This is a page made with Ruby on rails and react using 2 different repositories, one that host the api, and the other that host the front end code, so the code is more easy to mantain',
        desc: 'This is the first big description of this template projects, i will try to do my best to make them all different, but trying to they still have the same lengh, i dont use lorem fo this case so lets see how they result, this is writteng without any application or help of a machine so ejoy reading a lot of human text, this is over 100 lines but is near to the content of the orginal OH we finished.',
        tags: 'Css,Html,React,Ruby on Rails',
        live: '#',
        repo: '#',
        alt: 'placeholder',
        bAlt: 'Big_Placeholder',
    },
    {
        id: 1,
        title: 'Lasttask Web Store',
        subtitle: 'Lasttask Web Store',
        img: 'images/test.jpg',
        bImg: 'images/test.jpg',
        view: "This was one of my early projects i did when i was exploring the web development, it's a model of a webstore, have a shopping cart, product pages, account system and everything a store should need.",
        desc: 'This project, have the backend programmed from 0, using php, it does not use any kind of php framework, so the login and database system was made by hand, the use of frameworks for the front end maked this project more faster a easy to do, i used and edited some templates for it, the most important colors in this project are yellow, white and green, i learned a lot with this project so i am happy for done it',
        tags: 'Css,Html,React,PHP',
        live: '#',
        repo: 'https://github.com/eroiyo/lasttask',
        alt: 'placeholder',
        bAlt: 'Big_Placeholder',
    },
    {
        id: 2,
        title: 'Labyrinth-Generator',
        subtitle: 'Labyrinth-Generator',
        img: 'images/test.jpg',
        bImg: 'images/test.jpg',
        view: 'A maze generator using graphs, using a array matrix, commands for vectors, and binary logic to display the letters, this project is filled with tricky programming algroithms that are not commonly use, but when needed are very welcome.',
        desc: 'The graphs are extremely useful when we are talking about machine learning, because they are the perfect representation for a route of desicions, with it, we can automatize any activity, also they are useful when you are trying to do certain kind of simulations, in this project a lot of conditionals were remplaced simply using binary logic, because all the conditionals only have 2 incomes, so feel free to take the trick,',
        tags: 'Java',
        live: '#',
        repo: 'https://github.com/eroiyo/Labyrinth-Generator',
        alt: 'placeholder',
        bAlt: 'Big_Placeholder',
    },
    {
        id: 3,
        title: 'Conference Website',
        subtitle: 'Website created using an behance design as reference',
        img: 'images/conference.jpg',
        bImg: 'images/conference.jpg',
        view: 'A Conference webpage, created for an Capstone project to practice our html skills, we should pick a topic and use layout, colors and typographic already defined in a behance design made by Cindy Shin',
        desc: '',
        tags: 'Css,Html,Javascript',
        live: 'https://eroiyo.github.io/Calculator/',
        repo: 'https://github.com/eroiyo/Calculator/settings/pages',
        alt: 'conference',
        bAlt: 'conference',
    },
];
export default data;